---
title: "Extra Innings"
author: "Paul A. Hodgetts"
date: "21/09/2020"
output: html_document
---

**The information used here was obtained free of charge from and is copyrighted by Retrosheet. Interested parties may contact Retrosheet at** ["www.retrosheet.org".](https://www.retrosheet.org/)


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install packages, echo=FALSE, message=FALSE, warning=FALSE}
## uncomment any packages that need to be installed

#install.packages("tidyverse")         ## install tidyverse package
#install.packages("ggplot2")           ## install ggplot2 package
#install.packages("showtext")          ## install showtext package
#install.packages("visdat")            ## install visdat package

```

```{r libraries, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)     ## loads tidyverse library for working with data
library(ggplot2)       ## loads ggplot2 library for creating plots
library(showtext)      ## loads showtext library for accessing Google fonts
library(visdat)        ## loads visdat library for examining NA values
```

```{r import fonts, echo=FALSE, message=FALSE}
## add in fonts from Google fonts using showtext package
font_add_google(name = "DM Serif Text", family = "dm-serif-text")
font_add_google(name = "Jost", family = "jost-sans-serif")
showtext_auto()
```

```{r data function, echo=FALSE}

## read_gl function
## reads in a game log dataset from a given directory and creates a data object using a given name
## renames columns to something more representative and understandable
## adds a column with the year of the season
read_gl <- function(.data, file_dir){
  assign(.data, read.table(here::here(file_dir), header = FALSE, sep = ","), envir = .GlobalEnv)
  assign(.data, dplyr::rename(get(.data), date = V1, game_type = V2, weekday = V3, visiting_team = V4, visiting_league = V5, visiting_game_no = V6, home_team = V7, home_league = V8, home_game_no = V9, visiting_score = V10, home_score = V11, length_of_game_outs = V12, day_night = V13, completion = V14, forfeit = V15, protest = V16, parkid = V17, attendance = V18, time_of_game_mins = V19, visiting_scoreline = V20, home_scoreline = V21, visiting_ab = V22, visiting_hits = V23, visiting_dbls = V24, visiting_trpls = V25, visiting_hrs = V26, visiting_rbi = V27, visiting_sachit = V28, visiting_sacfly = V29, visiting_hbp = V30, visiting_bb = V31, visiting_ibb = V32, visiting_k = V33, visiting_sb = V34, visiting_cs = V35, visiting_odp = V36, visiting_ci = V37, visiting_lob = V38, visiting_pitcher_no = V39, visiting_ier = V40, visiting_ter = V41, visiting_wp = V42, visiting_balks = V43, visiting_putouts = V44, visiting_assists = V45, visiting_errors = V46, visiting_passedballs = V47, visiting_ddp = V48, visiting_dtp = V49, home_ab = V50, home_hits = V51, home_dbls = V52, home_trpls = V53, home_hrs = V54, home_rbi = V55, home_sachit = V56, home_sacfly = V57, home_hbp = V58, home_bb = V59, home_ibb = V60, home_k = V61, home_sb = V62, home_cs = V63, home_odp = V64, home_ci = V65, home_lob = V66, home_pitcher_no = V67, home_ier = V68, home_ter = V69, home_wp = V70, home_balks = V71, home_putouts = V72, home_assists = V73, home_errors = V74, home_passedballs = V75, home_ddp = V76, home_dtp = V77, umphome_id = V78, umphome_name = V79, ump1b_id = V80, ump1b_name = V81, ump2b_id = V82, ump2b_name = V83, ump3b_id = V84, ump3b_name = V85, umplf_id = V86, umplf_name = V87, umprf_id = V88, umprf_name = V89, visiting_mngrid = V90, visiting_mngrname = V91, home_mngrid = V92, home_mngrname = V93, win_pitchid = V94, win_pitchname = V95, lose_pitchid = V96, lose_pitchname = V97, sv_pitchid = V98, sv_pitchname = V99, game_winning_rbi_id = V100, game_winning_rbi_name = V101, vis_strtp_id = V102, vis_strtp_name = V103, home_strtp_id = V104, home_strtp_name = V105, vis_strt1_id = V106, vis_strt1_name = V107, vis_strt1_def = V108, vis_strt2_id = V109, vis_strt2_name = V110, vis_strt2_def = V111, vis_strt3_id = V112, vis_strt3_name = V113, vis_strt3_def = V114, vis_strt4_id = V115, vis_strt4_name = V116, vis_strt4_def = V117, vis_strt5_id = V118, vis_strt5_name = V119, vis_strt5_def = V120, vis_strt6_id = V124, vis_strt6_name = V122, vis_strt6_def = V123, vis_strt7_id = V124, vis_strt7_name = V125, vis_strt7_def = V126, vis_strt8_id = V127, vis_strt8_name = V128, vis_strt8_def = V129, vis_strt9_id = V130, vis_strt9_name = V131, vis_strt9_def = V132, home_strt1_id = V133, home_strt1_name = V134, home_strt1_def = V135, home_strt2_id = V136, home_strt2_name = V137, home_strt2_def = V138, home_strt3_id = V139, home_strt3_name = V140, home_strt3_def = V141, home_strt4_id = V142, home_strt4_name = V143, home_strt4_def = V144, home_strt5_id = V145, home_strt5_name = V146, home_strt5_def = V147, home_strt6_id = V148, home_strt6_name = V149, home_strt6_def = V150, home_strt7_id = V151, home_strt7_name = V152, home_strt7_def = V153, home_strt8_id = V154, home_strt8_name = V155, home_strt8_def = V156, home_strt9_id = V157, home_strt9_name = V158, home_strt9_def = V159, additional_info = V160, acquisition_info = V161), envir = .GlobalEnv)
  assign(.data, dplyr::mutate(get(.data), year = substr(.data$date, start = 1, stop = 4), .before = 1), envir = .GlobalEnv)
}
```

```{r data extra innings, echo=FALSE}
## read in game log datasets using the read_gl function
read_gl("gl2000_x", "data/gl2000_09/GL2000.TXT")
read_gl("gl2001_x", "data/gl2000_09/GL2001.TXT")
read_gl("gl2002_x", "data/gl2000_09/GL2002.TXT")
read_gl("gl2003_x", "data/gl2000_09/GL2003.TXT")
read_gl("gl2004_x", "data/gl2000_09/GL2004.TXT")
read_gl("gl2005_x", "data/gl2000_09/GL2005.TXT")
read_gl("gl2006_x", "data/gl2000_09/GL2006.TXT")
read_gl("gl2007_x", "data/gl2000_09/GL2007.TXT")
read_gl("gl2008_x", "data/gl2000_09/GL2008.TXT")
read_gl("gl2009_x", "data/gl2000_09/GL2009.TXT")
read_gl("gl2010_x", "data/gl2010_19/GL2010.TXT")
read_gl("gl2011_x", "data/gl2010_19/GL2011.TXT")
read_gl("gl2012_x", "data/gl2010_19/GL2012.TXT")
read_gl("gl2013_x", "data/gl2010_19/GL2013.TXT")
read_gl("gl2014_x", "data/gl2010_19/GL2014.TXT")
read_gl("gl2015_x", "data/gl2010_19/GL2015.TXT")
read_gl("gl2016_x", "data/gl2010_19/GL2016.TXT")
read_gl("gl2017_x", "data/gl2010_19/GL2017.TXT")
read_gl("gl2018_x", "data/gl2010_19/GL2018.TXT")
read_gl("gl2019_x", "data/gl2010_19/GL2019.TXT")
```

```{r data regular innings, echo=FALSE}
## read in game log datasets using the read_gl function
read_gl("gl2000_r", "data/gl2000_09/GL2000.TXT")
read_gl("gl2001_r", "data/gl2000_09/GL2001.TXT")
read_gl("gl2002_r", "data/gl2000_09/GL2002.TXT")
read_gl("gl2003_r", "data/gl2000_09/GL2003.TXT")
read_gl("gl2004_r", "data/gl2000_09/GL2004.TXT")
read_gl("gl2005_r", "data/gl2000_09/GL2005.TXT")
read_gl("gl2006_r", "data/gl2000_09/GL2006.TXT")
read_gl("gl2007_r", "data/gl2000_09/GL2007.TXT")
read_gl("gl2008_r", "data/gl2000_09/GL2008.TXT")
read_gl("gl2009_r", "data/gl2000_09/GL2009.TXT")
read_gl("gl2010_r", "data/gl2010_19/GL2010.TXT")
read_gl("gl2011_r", "data/gl2010_19/GL2011.TXT")
read_gl("gl2012_r", "data/gl2010_19/GL2012.TXT")
read_gl("gl2013_r", "data/gl2010_19/GL2013.TXT")
read_gl("gl2014_r", "data/gl2010_19/GL2014.TXT")
read_gl("gl2015_r", "data/gl2010_19/GL2015.TXT")
read_gl("gl2016_r", "data/gl2010_19/GL2016.TXT")
read_gl("gl2017_r", "data/gl2010_19/GL2017.TXT")
read_gl("gl2018_r", "data/gl2010_19/GL2018.TXT")
read_gl("gl2019_r", "data/gl2010_19/GL2019.TXT")
```

```{r prepare function, echo=FALSE}

## select and filter for only the necessary columns
## adds a column stating whether visitor or home team won
## saves time writing this as a function rather than writing the select and filter multiple times
## selects for columns in positions 1, 5, 8, and 11 through 13
## filters for extra inning games or regular inning games
## requires an existing data object
prepare_gl <- function(.data, filter_var){
  assign(.data, dplyr::select(get(.data), 1, 5, 8, 11:13), envir = .GlobalEnv)
  if(filter_var == "extra"){
    assign(.data, dplyr::filter(get(.data), length_of_game_outs > 54), envir = .GlobalEnv)
  }
  else if(filter_var == "regular"){
    assign(.data, dplyr::filter(get(.data), length_of_game_outs <= 54), envir = .GlobalEnv)
  }
  assign(.data, dplyr::mutate(get(.data), winning_team = case_when((.data$visiting_score > .data$home_score) ~ "visitor", 
                                                                   (.data$visiting_score < .data$home_score) ~ "home")), 
         envir = .GlobalEnv)
}
```

```{r prepare extra game logs, echo=FALSE}
## use the prepare_gl function to prepare a given gamelog
prepare_gl("gl2000_x", "extra")
prepare_gl("gl2001_x", "extra")
prepare_gl("gl2002_x", "extra")
prepare_gl("gl2003_x", "extra")
prepare_gl("gl2004_x", "extra")
prepare_gl("gl2005_x", "extra")
prepare_gl("gl2006_x", "extra")
prepare_gl("gl2007_x", "extra")
prepare_gl("gl2008_x", "extra")
prepare_gl("gl2009_x", "extra")
prepare_gl("gl2010_x", "etxra")
prepare_gl("gl2011_x", "extra")
prepare_gl("gl2012_x", "extra")
prepare_gl("gl2013_x", "extra")
prepare_gl("gl2014_x", "extra")
prepare_gl("gl2015_x", "extra")
prepare_gl("gl2016_x", "extra")
prepare_gl("gl2017_x", "extra")
prepare_gl("gl2018_x", "extra")
prepare_gl("gl2019_x", "extra")
```

```{r prepare regular game logs, echo=FALSE}
## use the prepare_gl function to prepare a given gamelog
prepare_gl("gl2000_r", "regular")
prepare_gl("gl2001_r", "regular")
prepare_gl("gl2002_r", "regular")
prepare_gl("gl2003_r", "regular")
prepare_gl("gl2004_r", "regular")
prepare_gl("gl2005_r", "regular")
prepare_gl("gl2006_r", "regular")
prepare_gl("gl2007_r", "regular")
prepare_gl("gl2008_r", "regular")
prepare_gl("gl2009_r", "regular")
prepare_gl("gl2010_r", "regular")
prepare_gl("gl2011_r", "regular")
prepare_gl("gl2012_r", "regular")
prepare_gl("gl2013_r", "regular")
prepare_gl("gl2014_r", "regular")
prepare_gl("gl2015_r", "regular")
prepare_gl("gl2016_r", "regular")
prepare_gl("gl2017_r", "regular")
prepare_gl("gl2018_r", "regular")
prepare_gl("gl2019_r", "regular")
```

```{r bind datasets, echo=FALSE}
## create a list of all dataframes
dfx <- grepl("_x", names(.GlobalEnv))
## run twice because it changes the number of items in the global environment-- 
## creating issues for the next line
dfx <- grepl("_x", names(.GlobalEnv))
names(dfx) <- names(.GlobalEnv)

## repeat above steps for regular inning games
dfr <- grepl("_r", names(.GlobalEnv))
dfr <- grepl("_r", names(.GlobalEnv))
names(dfr) <- names(.GlobalEnv)

## bind all extra inning dataframes using the created list
extras <- do.call(rbind, mget(names(dfx)[dfx]))

## bind all regular inning dataframes using the created list
reg <- do.call(rbind, mget(names(dfr)[dfr]))
```

```{r missing values, echo=FALSE, eval=FALSE}
## check for data for values
vis_dat(extras)
## check missing values
vis_miss(extras)

## check for data for values
vis_dat(reg)
## check missing values
vis_miss(reg)
```

```{r remove NA, echo=FALSE}
## remove NA values
## these are minimal so should not affect the outcome of the analysis
extras <- extras %>% 
  filter(winning_team != "NA")

## remove NA values
## these are minimal so should not affect the outcome of the analysis
reg <- reg %>% 
  filter(winning_team != "NA")
```

```{r extra inning game win count, echo=FALSE}
## extra inning wins/losses totals
extrawin_count <- count(extras, winning_team)
extrawin_count <- extrawin_count %>% 
  rename(count = n)

## extra inning wins/losses by year
extra_count_yr <- count(extras, winning_team, year) %>% 
  rename(count = n) %>% 
  unique()
```

```{r regular inning game win count, echo=FALSE}
## regular length wins/losses totals
regwin_count <- count(reg, winning_team)
regwin_count <- regwin_count %>% 
  filter(winning_team != "NA") %>% 
  rename(count = n)

## regular length wins/losses by year
reg_count_yr <- count(reg, winning_team, year) %>% 
  filter(winning_team != "NA") %>%
  rename(count = n) %>% 
  unique()
```

```{r count wins for season function, echo=FALSE}
## not necessary for current analysis but keeping

#count_wins <- function(.data, .output){
#  assign(.output, count(.data, winning_team), envir = .GlobalEnv)
#}
```

```{r ggplot theme, echo=FALSE, message=FALSE, warning=FALSE}
## creates a theme to be used with the plots below
## saves from having to type this for each chart
theme_noo <- theme_minimal()+
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major.y = element_line(colour = "black"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = "#eedfcc",
                                       colour = "#eedfcc"),
        panel.background = element_rect(fill = "#eedfcc",
                                        colour = "#eedfcc"),
        text = element_text(family = "jost-sans-serif"),
        axis.title.y = element_text(margin = margin(t = 0, b = 0, r = 20, l = 10)),
        axis.title.x = element_text(margin = margin(t = 20, b = 10, r = 0, l = 0)),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 18),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 18),
        strip.text = element_text(size = 14),
        plot.title = element_text(hjust = 0.5, 
                                  size = 24, 
                                  margin = margin(t = 5, b = 20, r = 0, l = 0),
                                  face = "bold"))
```

```{r chart1, echo=FALSE, fig.align = "center", message=FALSE, warning=FALSE}
ggplot(extrawin_count, aes(x = winning_team, y = count, fill = winning_team))+
  geom_bar(stat = "identity", alpha = 1)+
  labs(x = "Team Identity (Home or Visitor)",                                                     
       y = "Total Game Count",
       fill = "Legend",
       title = "Home vs. Visitor Wins & Losses in Extra Inning Games,\n 2000-2019 Total")+
  theme_noo+
  scale_fill_manual(values = c("#6495ed", "#ffc125"),
                    labels = c("Home", "Visitor"))+
  scale_y_continuous(expand = expansion(mult = c(0, 0)), breaks = c(0, 500, 1000, 1500, 2000, 2500, 3000, 3500))+
  scale_x_discrete(labels = c("Home", "Visitor"))+
  expand_limits(y = 3500)
```
<br><br><br><br><br>
```{r chart2, echo=FALSE, fig.align = "center", message=FALSE, warning=FALSE}
ggplot(regwin_count, aes(x = winning_team, y = count, fill = winning_team))+
  geom_bar(stat = "identity", alpha = 1)+
  labs(x = "Team Identity (Home or Visitor)",                                                     
       y = "Total Game Count",
       fill = "Legend",
       title = "Home vs. Visitor Wins & Losses in Regulation-Length Games,\n 2000-2019 Total")+
  theme_noo+
  scale_fill_manual(values = c("#6495ed", "#ffc125"),
                    labels = c("Home", "Visitor"))+
  scale_y_continuous(expand = expansion(mult = c(0, 0)), breaks = c(0, 2500, 5000, 7500, 10000, 12500, 15000, 17500, 20000, 22500, 25000))+
  scale_x_discrete(labels = c("Home", "Visitor"))+
  expand_limits(y = 25000)
```
<br><br><br><br><br>
```{r chart3, echo=FALSE, fig.height = 7, fig.width = 9, fig.align = "center", message=FALSE, warning=FALSE}
ggplot(extra_count_yr, aes(x = winning_team, y = count, fill = winning_team))+
  geom_bar(stat = "identity", alpha = 1)+
  labs(x = "Team Identity (Home or Visitor)",                                                     
       y = "Total Game Count",
       fill = "Legend",
       title = "Home vs. Visitor Wins & Losses in Extra Inning Games,\n by Year 2000-2019")+
  theme_noo+
  scale_fill_manual(values = c("#6495ed", "#ffc125"),
                    labels = c("Home", "Visitor"))+
  scale_x_discrete(labels = c("Home", "Visitor"))+
  scale_y_continuous(expand = expansion(mult = c(0, 0.05)))+
  facet_wrap(vars(year),
             nrow = 5,
             scales = "free_y")
```
<br><br><br><br><br>
```{r chart4, echo=FALSE, fig.height = 7, fig.width = 9, fig.align = "center", message=FALSE, warning=FALSE}
ggplot(reg_count_yr, aes(x = winning_team, y = count, fill = winning_team))+
  geom_bar(stat = "identity", alpha = 1)+
  labs(x = "Team Identity (Home or Visitor)",                                                     
       y = "Total Game Count",
       fill = "Legend",
       title = "Home vs. Visitor Wins & Losses in Regulation-Length Games,\n by Year 2000-2019")+
  theme_noo+
  scale_fill_manual(values = c("#6495ed", "#ffc125"),
                    labels = c("Home", "Visitor"))+
  scale_x_discrete(labels = c("Home", "Visitor"))+
  scale_y_continuous(expand = expansion(mult = c(0, 0.05)))+
  facet_wrap(vars(year),
             nrow = 5,
             scales = "free_y")
```
